#!/usr/bin/env python
import matplotlib.pyplot as plt
import numpy as np
import argparse
import json


parser = argparse.ArgumentParser()
parser.add_argument('x', help='key for x-axis')
parser.add_argument('y', help='key for y-axis')
parser.add_argument('path', nargs='+', help='path to json file')
parser.add_argument('--window-size', type=int, default=1, help='window size of moving average')
args = parser.parse_args()

window_size = args.window_size
window_mask = np.ones((window_size), dtype=np.float32) / window_size

for i, path in enumerate(args.path):
    x_values = []
    y_values = []
    with open(path, 'r') as f:
        for line in f.readlines():
            data = json.loads(line)
            x_values.append(data[args.x])
            y_values.append(data[args.y])
    x_valules = np.array(x_values)
    y_valules = np.array(y_values)
    moving_average = np.convolve(y_values, window_mask, mode='same')
    plt.plot(x_values, moving_average, label=path)
plt.legend()
plt.xlabel(args.x)
plt.ylabel(args.y)
plt.show()
